### ISSUE TITLE
Create automatic testing suite for ERC20 and oracle wrapper contracts

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-ink-wrapper#20]
## Context 
Our wrapper contracts are using the chain extension, so we have to compile them to WASM. Meaning we cannot use testing suites for EVM contracts but we can also not write unit tests to the same file. We could, however, have tests that deploy the contracts to our chain and then do automated tests with the deployed contracts. 

Solang is doing tests similar to this. They define some helper functions [here](https://github.com/hyperledger/solang/blob/main/integration/polkadot/index.ts) and in their actual test implementation (e.g. [this](https://github.com/hyperledger/solang/blob/main/integration/polkadot/UniswapV2ERC20.spec.ts)), they use those helper functions to deploy and interact with the contracts on-chain, asserting certain values as results of the interactions.

## Solution
We will create an automatic testing suite that uses a local standalone chain to deploy and interact with the compiled smart contracts. The standalone chain features the exact same chain extension that is also live on Pendulum/Amplitude/Foucoco.

## Tasks
- [ ] Wait until [this](https://github.com/pendulum-chain/pendulum/issues/249) ticket is completed. 
- [ ] Set up a standalone test chain in this repository using the [template](https://github.com/substrate-developer-hub/substrate-node-template/tree/main) and include 1) the chain_extension extract as part of [249](https://github.com/pendulum-chain/pendulum/issues/249), 2) the orml_tokens pallet, and 3) the DIA pallet. All of these are required to configure the chain extension similarly to how it is set up on our main chains.
- [ ] Create a new directory `tests` and create a test suite for the ERC20 and price oracle wrapper contract. The ERC20 test can be adopted from [this](https://github.com/hyperledger/solang/blob/main/integration/polkadot/UniswapV2ERC20.spec.ts) file, both tests should follow a similar structure.
- [ ] Add instructions on how to run the tests to the README. It should describe how the automatic testing works, and mention the commands needed to run it. 

To do that, we can re-use the tests of [this](https://github.com/hyperledger/solang/blob/main/integration/polkadot/UniswapV2ERC20.spec.ts) file.

**Comment by ebma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-ink-wrapper/20?planning-poker) with Zenhub @ashneverdawn @TorstenStueber

**Comment by prayagd** [comment]
ok got it, Moving it to icebox then as wasm deploy not priority right now
