### ISSUE TITLE
Fix informational issues raised in audit report

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-ink-wrapper#23]
The following informational issues were raised in the audit report. We should fix all of them. It's okay to fix them in just one PR.
Please find the details for each issue in the [audit report](https://wp.hacken.io/wp-content/uploads/2023/08/SatoshiPay_SC-Audit-Report_28_07_SA-1595.pdf).

## Tasks:
- [x] I01. Solidity Style Guide Violation: Naming mismatch
- [x] I02. Functions That Should Be External
- [x] I03. Solidity Style Guide Violation: Order Of Layout
- [x] I04. Inefficient Gas Modeling
- [x] I05. Redundant Function Virtualization
- [x] I06. Solidity Style Guide: mixedCase in State Variables Names

**Comment by ebma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-ink-wrapper/23?planning-poker) with Zenhub @ashneverdawn @TorstenStueber
